### ISSUE TITLE
Instantaneous simulations

### ISSUE THREAD

**Issue by h-oll** [h-oll/netsquid-private#1]
Hi Chinte, 

thanks for all the work done and uploaded. I was trying to understand what you said yesterday during the call with SAP about 'disabling the physics simulation'. 

I believe what you are meaning is that what you do in this function https://github.com/h-oll/netsquid-private/blob/31b39ac7d47b60519ea8dd8faea43284633552bf/BB84/BB84_v1_5.py#L44
is not associated to a physical model, and thus is not simulated physically, and so is instantaneous. 

Is that what you meant ?

**Comment by LiaoChinTe** [comment]
Hi Harold,

Not really. What I mean by disable physical feature is : For example, 
we are able to make an "ideal" fiber that can pass a qubit without any loss in a simulation using NetSquid. Or we can make an "ideal" quantum memory that can store qubits without affected by noise over time. And of course that's not practical in real world. So NetSquid provides default configuration for us to try out. We can even apply probabilities to simulate loss.  

Line 172 is where I applied LossModel to QuantumFiber. (loss model parameters are given when the protocol is initialized)
For quantum memory simulation, you will find similar assignment at line 28 in Others/QMemory/QMemoryNoiceSim.py 

BTW, Those plot I made are all based on different physical configuration as well.

Hope this answers your question.

**Comment by h-oll** [comment]
Hi,

Thanks for your answer. Does it speed up the simulation when you put
everything to perfect ?

H

LiaoChinTe <notifications@github.com> writes:

> Hi Harold,
>
> Not really. What I mean by disable physical feature is : For example,
> we are able to make an "ideal" fiber that can pass a qubit without any loss in a simulation using NetSquid. Or we can make an "ideal" quantum memory that can store qubits without affected by noise over time. And of
> course that's not practical in real world. So NetSquid provides default configuration for us to try out. We can even apply probabilities to simulate loss.
>
> Line 172 is where I applied LossModel to QuantumFiber. (loss model parameters are given when the protocol is initialized)
> For quantum memory simulation, you will find similar assignment at line 28 in Others/QMemory/QMemoryNoiceSim.py
>
> BTW, Those plot I made are all based on different physical configuration as well.
>
> Hope this answers your question.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 
Harold OLLIVIER
+33 617 103 898

**Comment by LiaoChinTe** [comment]
I don't have statistical proof yet, but in software point of view the answer should be yes, it should run faster if we apply ideal component, because of less computation.
